updated script to read local file first

diff --git a/copy_from_to b/copy_from_to
--- a/copy_from_to
+++ b/copy_from_to
@@ -18,14 +18,14 @@ ${THISSCRIPTNAME}   from_path   to_path
 fi
 
 if command -v wget >/dev/null 2>&1; then
-    echo '.'
+    echo '1'
 else
     echo "wget not found. please install" 
     exit 69
 fi
 
 if command -v rsync >/dev/null 2>&1; then
-    echo '.'
+    echo '2'
 else
     echo "rsync not found. please install" 
     exit 69
@@ -33,7 +33,7 @@ fi
 
 
 if command -v find >/dev/null 2>&1; then
-    echo '.'
+    echo '3'
 else
     echo "find not found. please install" 
     exit 69
@@ -41,21 +41,25 @@ fi
 
 
 if command -v sed >/dev/null 2>&1; then
-    echo '.'
+    echo '4'
 else
     echo "sed not found. please install" 
     exit 69
 fi
 
-load_execute_command(){
-    EXECOMCLI=$(wget --quiet --no-check-certificate https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_command -O -  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
-    eval """${EXECOMCLI}"""
-    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading execute_command \n \n " && exit 130; )
-} # end function load_execute_command
-load_execute_command
+THISSCRIPTNAME=`basename "$0"`
+load_execute_command_wget(){
+    local provider="/_/clis/execute_command_intuivo_cli/execute_command"
+    [   -e "${provider}"  ] && source "${provider}"
+    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_command -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading execute_command \n \n " && exit 69; )
+} # end load_execute_command_wget
+load_execute_command_wget
+
+
 
 if command -v anounce >/dev/null 2>&1; then
-    echo '.'
+    echo '5'
 else
     echo "anounce not found. Check Your internet connection" 
     exit 69
