updated nurs and ersetses and added open function test

diff --git a/doe b/doe
--- a/doe
+++ b/doe
@@ -24,13 +24,13 @@ upcase_downcase_capitalize(){
 
     local fromsource="""${1}"""
     local totarget="""${2}"""
-	local changelogfile="$(echo "$(date +%Y%m%d%H%M)_${fromsource}_${totarget}.log")"
-	Rerunchangelogfile="$(echo "$(date +%Y%m%d%H%M)_${fromsource}_${totarget}.sh")"
+    local changelogfile="$(echo "$(date +%Y%m%d%H%M)_${fromsource}_${totarget}.log")"
+    Rerunchangelogfile="$(echo "$(date +%Y%m%d%H%M)_${fromsource}_${totarget}.sh")"
     echo  "" > ${Rerunchangelogfile}
     echo  "" > ${changelogfile}
-	[ ! -e .gitignore ] && echo .git > .gitignore
-	echo ${changelogfile} >> .gitignore
-	echo ${Rerunchangelogfile} >> .gitignore
+    [ ! -e .gitignore ] && echo .git > .gitignore
+    echo ${changelogfile} >> .gitignore
+    echo ${Rerunchangelogfile} >> .gitignore
 
     if [[ -z "${fromsource}" ]]  ||  [[ -z "${totarget}" ]] ; then
     {
@@ -64,22 +64,20 @@ upcase_downcase_capitalize(){
     }
     fi
 
-	[ ! -e .ersetzeignore_dirs ] && echo .git > .ersetzeignore_dirs
+    [ ! -e .ersetzeignore_dirs ] && echo .git > .ersetzeignore_dirs
     echo ${changelogfile} >> .ersetzeignore_files
     echo ${Rerunchangelogfile} >> .ersetzeignore_files
 
     [ ! -e .nurignore_dirs ] && echo .git > .nurignore_dirs
-	echo ${changelogfile} >> .nurignore_files
+    echo ${changelogfile} >> .nurignore_files
     echo ${Rerunchangelogfile} >> .nurignore_files
 
-	exec 3>&1 1>>${changelogfile} 2>&1  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
+    exec 3>&1 1>>${changelogfile} 2>&1  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
 
     john_doe_it "${fromsource}" "${totarget}"  | tee /dev/fd/3  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
     john_doe_it "${lower_case_fromsource}" "${lower_case_totarget}"  | tee /dev/fd/3  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
-# echo "
     john_doe_it "${upper_case_fromsource}" "${upper_case_totarget}"  | tee /dev/fd/3  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
     john_doe_it "${capitalized_fromsource}" "${capitalized_totarget}"  | tee /dev/fd/3  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
-# "
     return 0
 } # end upcase_downcase_capitalize
 
@@ -89,36 +87,39 @@ john_doe_it(){
     local totarget="""${2}"""
 
     echo "--------------------start äö "${fromsource}" "${totarget}""
-	echo äö "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	local two aoet=$(äö "${fromsource}" "${totarget}"  2>&1; ) #capture stdout and stderr
-	if [ $? != 0 ] ; then
+    echo äö "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
+    local two aoet=""
+    aoet=$(äö "${fromsource}" "${totarget}"  2>&1; ) #capture stdout and stderr
+    if [ $? != 0 ] ; then
     {
-        if [ "${aoet}" ==  *"SORRY NO FOUND OCCURENCES"* ] ; then
+        if [[ "${aoet}" ==  *"SORRY NO FOUND OCCURENCES"* ]] ; then
         {
             (echo "# Not Found." >> ${Rerunchangelogfile})
-        } else {
+        }
+        else
+        {
             (echo "# ERROR Something went wrong.")
             while read -r two; do
-		    if [ -n "${two}" ]  ; then # if not empty
-			     (echo "${two}" >> ${Rerunchangelogfile})
-		    fi
-	        done <<< "${aoet}"
+            {
+              [[ -z "${two}" ]] && continue # if not empty
+              (echo "${two}" >> ${Rerunchangelogfile})
+            }
+            done <<< "${aoet}"
             (echo "# Failed." >> ${Rerunchangelogfile})
         }
         fi
     }
     fi
-	wait
+    wait
     echo "------------------------------end   äö "${fromsource}" "${totarget}""
-	echo "----------------------------------------------------------start to_this "${fromsource}" "${totarget}""
-	to_this "${fromsource}" "${totarget}"
-	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile})
-# echo "
-``
-	to_this "${fromsource}" "${totarget}"
-	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile})
+    echo "----------------------------------------------------------start to_this "${fromsource}" "${totarget}""
+    to_this "${fromsource}" "${totarget}"
+    echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
+    [ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile})
+
+    to_this "${fromsource}" "${totarget}"
+    echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
+    [ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile})
 
 	to_this "${fromsource}" "${totarget}"
 	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
@@ -130,9 +131,9 @@ john_doe_it(){
 
 	wait
 	echo "----------------------------------------------------------------------------end to_this "${fromsource}" "${totarget}""
-	git add .
-	git commit -m "john doe it dö did "${fromsource}" "${totarget}""
-# "
+	#git add .
+	#git commit -m "john doe it dö did "${fromsource}" "${totarget}""
+
 } # end upcase_downcase_capitalize
 
 
diff --git a/ersetzeindatei b/ersetzeindatei
--- a/ersetzeindatei
+++ b/ersetzeindatei
@@ -5,7 +5,7 @@
 #
 #
 THISSCRIPTNAME=`basename "$0"`
-#bash shell script check input argument
+# bash shell script check input argument
 FAIL=0;
 echo "   ";
 if [ -z "$1" ]
@@ -57,6 +57,23 @@ if [ -z "$4" ]
 
 fi
 
+ ####        ####       #            ####       #####        ####
+ ####        ####       #            ####       #####        ####
+#    #      #    #      #           #    #      #    #      #
+#    #      #    #      #           #    #      #    #      #
+#           #    #      #           #    #      #    #       ####
+#           #    #      #           #    #      #    #       ####
+#           #    #      #           #    #      #####            #
+#           #    #      #           #    #      #####            #
+#    #      #    #      #           #    #      #   #       #    #
+#    #      #    #      #           #    #      #   #       #    #
+ ####        ####       ######       ####       #    #       ####
+ ####        ####       ######       ####       #    #       ####
+
+#
+# COLORS - Ouput - Start
+#
+
 red=`tput setaf 1`
 cyan=`tput setaf 6`
 green=`tput setaf 2`
@@ -77,6 +94,10 @@ NORMAL=$(tput sgr0)
 BLINK=$(tput blink)
 REVERSE=$(tput smso)
 UNDERLINE=$(tput smul)
+
+#
+# COLORS - Ouput - end
+#
 
 FILE="$1";
 SEEKER="./ack";
@@ -103,26 +124,7 @@ msg_green () {
 }
 
 trap '{ msg_red " KEYBOARD INTERRUPT."; exit 130; }' INT
-#
-# C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --Start
-#
-test_positives(){
-  KIND=""
-  ls werwerwerwerwerwerwerwerwerwerwerr >/dev/null 2>&1;
-  if (( $? == 0 )) ;  then  # Intel processor
-    KIND="INTEL"
-  fi
-  if [ $? == 0 ]; then   # Mac Intel processor
-    KIND="${KIND}MAC"
-  fi
-  echo "${KIND}"
-}
-PROCESSOR_ERROR=$(test_positives)
-# DEBUG MACPOSITIVE MACPOSITIVE echo "${PROCESSOR_ERROR}"
-# DEBUG MACPOSITIVE exit 1
-#
-# C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --End
-#
+
 
 #
 # C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --Start
@@ -244,12 +246,27 @@ fi
 # S E E K I N G   I N S T A L L    C H E C K  - Start
 #
 if command -v sift >/dev/null 2>&1; then
-    {
-        msg_green " sift INSTALLED."
-        #-i, --ignore-case      case insensitive (default: off) Case sentive by default
-        #-n, --line-number      show line numbers (default: off)
-        #-Q, --literal          treat pattern as literal, quote meta characters
-        #--output-sep=          output separator (default: "\n")
+  {
+      if [ $VERBOSE -eq 1 ] ; then
+        {
+            #  NOT Colored
+            if [ ! -z "$COLORED" ] ; then
+                {
+                  echo " sift INSTALLED."
+                }
+              else
+                {
+                  msg_green " sift INSTALLED."
+                }
+              fi
+
+        }
+      fi
+      #-i, --ignore-case      case insensitive (default: off) Case sentive by default
+      #-n, --line-number      show line numbers (default: off)
+      #-Q, --literal          treat pattern as literal, quote meta characters
+      #--output-sep=          output separator (default: "\n")
+      #--no-color             disable colored output
       # Error: sift Error: files skipped due to very long lines
       # Fix:
       #   REF: https://github.com/svent/sift/issues/16
@@ -258,94 +275,100 @@ if command -v sift >/dev/null 2>&1; then
       #    --err-skip-line-length to skip these errors
       #    --blocksize to specify a larger blocksize, allowing to search files with very long lines. Example: --blocksize 10M
         SEEKER="sift -nQ  --blocksize 50M";
-        IGNORE_DIR="exclude-dirs";
-        IGNORE_FILE="exclude-files";
-        PRINTCOMMAND="-l --output-sep=\"\\x00\"";
-    }
+      IGNORE_DIR="exclude-dirs";
+      IGNORE_FILE="exclude-files";
+      PRINTCOMMAND="-l --output-sep=\"\\x00\"";
+  }
 else
+  {
+
+  if command -v ag >/dev/null 2>&1; then
     {
 
-    if command -v ag >/dev/null 2>&1; then
-        {
+                  msg_green " ag INSTALLED."
+      # -s  is for case sensitive
+      #-Q --literal            Don't parse PATTERN as a regular expression
+      #-0 --null --print0      Separate filenames with null (for 'xargs -0')
+      #--nocolor               Disable colors (Enabled by default)
+              SEEKER="ag -sQ ";
+      IGNORE_DIR="ignore";
+      IGNORE_FILE="ignore";
+      PRINTCOMMAND="-l --print0";
+    }
+  else
+    {
 
-        msg_green " ag INSTALLED."
-        # -s  is for case sensitive
-        #-Q --literal            Don't parse PATTERN as a regular expression
-        #-0 --null --print0      Separate filenames with null (for 'xargs -0')
-        SEEKER="ag -sQ ";
-        IGNORE_DIR="ignore";
-        IGNORE_FILE="ignore";
+    # msg_red " NEED TO INSTALL ag."
+    # msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
+    # sudo apt-get install silversearcher-ag -fy
+
+    if command -v ack >/dev/null 2>&1; then
+      {
+
+                  msg_green " ack INSTALLED."
+        # ack is            case sensitve by default
+        # --print0          Print null byte as separator between filenames, only works with -f, -g, -l, -L or -c.
+        # -Q, --literal     Quote all metacharacters; PATTERN is litera
+        # --nocolor         Highlight the matching text (default: on unless --nocolor)
+        #
+        # Ack DOES NOT SUPPORT HIDDING LINE NUMBERS
+                SEEKER="ack -Q ";
+        IGNORE_DIR="ignore-dir";
+        IGNORE_FILE="ignore-file";
         PRINTCOMMAND="-l --print0";
-        }
+
+      }
     else
+      {
+
+      # msg_red " NEED TO INSTALL ack."
+      # msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
+      # sudo apt-get install ack-grep -fy
+
+      ls ./ack  | egrep 'ack' &>/dev/null
+      err_buff=$?
+            if [[ "${PROCESSOR_ERROR}" == "MAC" ]] && [ $err_buff == 1 ]; then
+        {
+                msg_green " ./ack INSTALLED."
+                SEEKER="./ack -Q ";
+          IGNORE_DIR="ignore-dir";
+          IGNORE_FILE="ignore-file";
+          PRINTCOMMAND="-l --print0";
+        }
+      elif [[ "${PROCESSOR_ERROR}" == "INTEL" ]] && (( $err_buff == 0 )); then
         {
 
-        #msg_red " NEED TO INSTALL ag."
-        #msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
-        #sudo apt-get install silversearcher-ag -fy
+                    msg_green " ./ack INSTALLED."
+                  SEEKER="./ack -Q ";
+          IGNORE_DIR="ignore-dir";
+          IGNORE_FILE="ignore-file";
+          PRINTCOMMAND="-l --print0";
+        }
+      else
+        {
 
-        if command -v ack >/dev/null 2>&1; then
-            {
+        # msg_red " NEED TO INSTALL ./ack "
+        # msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
+        # cp ~/bin/ack .
 
-            msg_green " ack INSTALLED."
-            # ack is case sensitve by default
-            # --print0 Print null byte as separator between filenames, only works with -f, -g, -l, -L or -c.
-            # -Q, --literal                 Quote all metacharacters; PATTERN is litera
-            SEEKER="ack -Q ";
-            IGNORE_DIR="ignore-dir";
-            IGNORE_FILE="ignore-file";
-            PRINTCOMMAND="-l --print0";
+        if command -v grep >/dev/null 2>&1; then
+          {
+          #-i, --ignore-case
+          # Perform case insensitive matching.  By default, grep is case sensitive.
+          #
+          #-E, --extended-regexp
+          # Interpret pattern as an extended regular expression (i.e. force grep to behave as
+          # egrep).
+          #
+          #-e pattern, --regexp=pattern
+          # Specify a pattern used during the search of the input: an input line is selected if it
+          # matches any of the specified patterns.  This option is most useful when multiple -e
+          # options are used to specify multiple patterns, or when a pattern begins with a dash
+          # (`-').
+          #-F, --fixed-strings
+          # Interpret pattern as a set of fixed strings (i.e. force grep to behave as fgrep).
+          # --color=never     disable color
 
-            }
-        else
-            {
-
-            #msg_red " NEED TO INSTALL ack."
-            #msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
-            #sudo apt-get install ack-grep -fy
-
-            ls ./ack  | egrep 'ack' &>/dev/null
-            err_buff=$?
-            if [[ "${PROCESSOR_ERROR}" == "MAC" ]] && [ $err_buff == 1 ]; then
-            {
-                msg_green " ./ack INSTALLED."
-                SEEKER="./ack -Q ";
-                IGNORE_DIR="ignore-dir";
-                IGNORE_FILE="ignore-file";
-                PRINTCOMMAND="-l --print0";
-            }
-            elif [[ "${PROCESSOR_ERROR}" == "INTEL" ]] && (( $err_buff == 0 )); then
-                {
-
-                msg_green " ./ack INSTALLED."
-                SEEKER="./ack -Q ";
-                IGNORE_DIR="ignore-dir";
-                IGNORE_FILE="ignore-file";
-                PRINTCOMMAND="-l --print0";
-                }
-            else
-                {
-
-                #msg_red " NEED TO INSTALL ./ack "
-                #msg_red " ENTER SUDO PASSWORD AND PRESS ENTER."
-                # cp ~/bin/ack .
-
-                if command -v grep >/dev/null 2>&1; then
-                    {
-                    #-i, --ignore-case
-                    # Perform case insensitive matching.  By default, grep is case sensitive.
-                    #
-                    #-E, --extended-regexp
-                    # Interpret pattern as an extended regular expression (i.e. force grep to behave as
-                    # egrep).
-                    #
-                    #-e pattern, --regexp=pattern
-                    # Specify a pattern used during the search of the input: an input line is selected if it
-                    # matches any of the specified patterns.  This option is most useful when multiple -e
-                    # options are used to specify multiple patterns, or when a pattern begins with a dash
-                    # (`-').
-                    #-F, --fixed-strings
-                    # Interpret pattern as a set of fixed strings (i.e. force grep to behave as fgrep).
           #
           # grep (GNU grep) 2.25
           # -l, --files-with-matches
@@ -363,37 +386,38 @@ else
           #    -print0, perl -0, sort -z, and xargs -0  to  process  arbitrary
           #    file names, even those that contain newline characters.
           #
-                    msg_green " grep INSTALLED."
-                    SEEKER="grep -rnE ";
-                    IGNORE_DIR="exclude-dir";
-                    IGNORE_FILE="exclude";
-                    FILESCOMMAND=".";
-                #PRINTCOMMAND="-l --print0";
-                    PRINTCOMMAND="-l --null";
-                    }
-                else
-                    {
 
-                    echo "${green} ${red} CANNOT SEARCH ....MISSING SEARCHER SIFT, ACK, AG, ./ACK, ./AG, ./SIFT OR GREP  ";
-                    exit 1;
-                    #msg_red " NEED TO INSTALL grep."
-                    }
-                fi
-                }
-            fi
-            }
+                  msg_green " grep INSTALLED."
+                SEEKER="grep -nrE "
+          IGNORE_DIR="exclude-dir";
+          IGNORE_FILE="exclude";
+          FILESCOMMAND=".";
+          # PRINTCOMMAND="-l --print0";
+          PRINTCOMMAND="-l --null";
+          }
+        else
+          {
+
+                echo "${green} ${red} CANNOT SEARCH ....MISSING SEARCHER SIFT, ACK, AG, ./ACK, ./AG, ./SIFT OR GREP  ";
+                exit 1;
+            #msg_red " NEED TO INSTALL grep."
+          }
         fi
         }
+      fi
+      }
     fi
     }
+  fi
+  }
 fi
 #CHECK FOR CHOICE FORCE IT
-if command -v ${DEFAULTSEEKER} >/dev/null 2>&1; then
+if command -v "${DEFAULTSEEKER}" >/dev/null 2>&1; then
     {
         SEEKER="${DEFAULTSEEKER}";
 
         echo "${cyan}  using chosen option ... ${SEEKER}  "
-        msg_green " ${SEEKER} INSTALLED."
+                msg_green " ${SEEKER} INSTALLED."
 
         # make case sentive for local sift
         if [ $DEFAULTSEEKER == "sift" ]; then
@@ -402,10 +426,10 @@ if command -v ${DEFAULTSEEKER} >/dev/null 2>&1; then
             IGNORE_DIR="exclude-dirs";
             IGNORE_FILE="exclude-files"
             PRINTCOMMAND="-l --output-sep=\"\\x00\"";
-            }
+        }
         fi
         # make case sentive for ag
-        if [ $DEFAULTSEEKER == "ag" ]; then
+        if [[ "$DEFAULTSEEKER" == "ag" ]] ; then
         {
             SEEKER="ag -sQ "
             IGNORE_DIR="ignore";
@@ -425,29 +449,29 @@ if command -v ${DEFAULTSEEKER} >/dev/null 2>&1; then
         # make case sentive for local ./ack
         if [ $DEFAULTSEEKER == "./ack" ]; then
         {
-            SEEKER="./ack -Q "
+                SEEKER="./ack -Q "
             IGNORE_DIR="ignore-dir";
             IGNORE_FILE="ignore-file";
             PRINTCOMMAND="-l --print0";
         }
         fi
-        #use extended expressions
+        # use extended expressions
         if [ $DEFAULTSEEKER == "grep" ]; then
         {
             SEEKER="grep -rnE "
             IGNORE_DIR="exclude-dir";
             IGNORE_FILE="exclude";
             FILESCOMMAND=".";
-            #PRINTCOMMAND="-l --print0";
+            # PRINTCOMMAND="-l --print0";
             PRINTCOMMAND="-l --null";
         }
         fi
     }
 else
-    {
+{
     #echo "${red}   your seeker ${DEFAULTSEEKER} was not found!"
     echo "${cyan}  using ...${SEEKER}  "
-    }
+    
 fi
 
 
@@ -506,21 +530,22 @@ DIRSTOEXCLUDE=".cargo
 .ecryptfs
 .gvfs
 .git
+.idea
 .vagrant
 .servo
 coverage
 AbsoluteUrlBundle
 app/Stubs
 bower_components
-node_modules
 cache
 .cache
 dist
+node_modules
 python
 storage/debugbar
 storage/logs
 target
-
+tmp
 log
 ports
 app/Stubs
@@ -532,7 +557,7 @@ app/logs
 app/session
 ${MOREIGNORE_DIRS}"
 
-
+IGNORELIST=""
 
     while read -r ONE_FILENAME; do
       # if not empty
@@ -559,28 +584,34 @@ ${MOREIGNORE_DIRS}"
 #             $PRINTCOMMAND  the pipiing command to funel to results to replacer program
 #             $IGNORELIST  construct of ignored files
 #             halts execution if not found
+
+
 #
 SEEKING="$2";
-echo "${reset} ${green} Finding ${reset} $SEEKING ${green}                 with  ${SEEKER} ."
-echo "   ";
+                echo "${RESET} ${GREEN} Finding ${RESET} $SEEKING ${GREEN}                 with  ${SEEKER} ."
+                echo "   ";
 
-echo "   ";
+                echo "   ";
 echo "${reset} ${green} Seek ignoring $(echo ${IGNORELIST} | sed  "s@${EXCLUDEDIR}@@g" | sed  "s@${EXCLUDEFILE}@@g"  | sed  "s@ @,@g") with ${SEEKER} -- "
 #
 # S E E K I N G   I N S T A L L    C H E C K  - End
 #
+# echo "${CYAN}  ack  --ignore=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
+# echo "${CYAN}  ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
+# echo "${CYAN}  grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs \"${SEEKING}\" "
 
-
-# echo "${cyan}  ack  --ignore=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
-# echo "${cyan}  ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
-# echo "${cyan}  grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs \"${SEEKING}\" "
-echo "   ";
+# If verbose  and # not PIPED
+if [ $VERBOSE -eq 1 ] && [ -z "$PIPED" ]; then
+  {
+    echo "   ";
+  }
+fi
 err_buff=$?;
 # THIS IS GREP FOR LINUX
 # ack  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs "$SEEKING"
 # ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs "$SEEKING"
 # grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs "$SEEKING"
-#THIS IS GREP FOR MAC
+# THIS IS GREP FOR MAC
 # grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs -e "$SEEKING" *
 
 if [[ $SEEKING == *"/"* ]]
@@ -588,22 +619,22 @@ then
 {
 
 
-echo "${cyan}   ${SEEKER} \"${SEEKING}\" ${FILESCOMMAND} ${IGNORELIST}   ${FILE}"
+        echo "${cyan}   ${SEEKER} \"${SEEKING}\" ${FILESCOMMAND} ${IGNORELIST}   ${FILE}"
                 ${SEEKER} "$SEEKING" ${FILESCOMMAND}     ${IGNORELIST}   ${FILE}
                 ${SEEKER} "$SEEKING" ${FILESCOMMAND}     ${IGNORELIST}   ${FILE} | ${SEEKER} "$SEEKING" ${FILESCOMMAND}  &>/dev/null
-}
-else
-{
+      }
+      else
+      {
 
-echo "${cyan}   ${SEEKER} \"${SEEKING}\" ${FILESCOMMAND} ${IGNORELIST}   ${FILE}"
+        echo "${cyan}   ${SEEKER} \"${SEEKING}\" ${FILESCOMMAND} ${IGNORELIST}   ${FILE}"
                 ${SEEKER} "$SEEKING" ${FILESCOMMAND}     ${IGNORELIST}   ${FILE}
                 ${SEEKER} "$SEEKING" ${FILESCOMMAND}     ${IGNORELIST}   ${FILE} | ${SEEKER} "$SEEKING" ${FILESCOMMAND}  &>/dev/null
 }
 fi
 
 # If  | egrep "$SEEKING" &>/dev/null | returned an error....so it was... it was found/not found say it and stop execution for not found
-#if [ ! $? -eq 0 ] ; then #mac
-#if (( $? == 0 )) ;  then #work
+# if [ ! $? -eq 0 ] ; then #mac
+# if (( $? == 0 )) ;  then #work
 
 ################       ##############         ####          ####    ####        ####    ################
 ################       ##############         ####          ####    ####        ####    ################
