added hash tag to Failed message

diff --git a/doe b/doe
--- a/doe
+++ b/doe
@@ -88,27 +88,27 @@ john_doe_it(){
     echo "--------------------start äö "${fromsource}" "${totarget}""
 	echo äö "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
 	äö "${fromsource}" "${totarget}"
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "Failed." >> ${Rerunchangelogfile}) && exit 1
+	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile}) && exit 1
 
 	wait
     echo "------------------------------end   äö "${fromsource}" "${totarget}""
 	echo "----------------------------------------------------------start to_this "${fromsource}" "${totarget}""
 	to_this "${fromsource}" "${totarget}"
 	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "Failed." >> ${Rerunchangelogfile}) && exit 1
+	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile}) && exit 1
 # echo "
 
 	to_this "${fromsource}" "${totarget}"
 	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "Failed." >> ${Rerunchangelogfile}) && exit 1
+	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile}) && exit 1
 
 	to_this "${fromsource}" "${totarget}"
 	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "Failed." >> ${Rerunchangelogfile}) && exit 1
+	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile}) && exit 1
 
 	to_this "${fromsource}" "${totarget}"
 	echo to_this "${fromsource}" "${totarget}" >> ${Rerunchangelogfile}
-	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "Failed." >> ${Rerunchangelogfile}) && exit 1
+	[ $? != 0 ] && (echo "ERROR Something went wrong.") && (echo "# Failed." >> ${Rerunchangelogfile}) && exit 1
 
 	wait
 	echo "----------------------------------------------------------------------------end to_this "${fromsource}" "${totarget}""
