updated nur to use pt as faster searcher than sift

diff --git a/ersetzeindatei b/ersetzeindatei
--- a/ersetzeindatei
+++ b/ersetzeindatei
@@ -100,6 +100,18 @@ NORMAL=$(tput sgr0)
 BLINK=$(tput blink)
 REVERSE=$(tput smso)
 UNDERLINE=$(tput smul)
+[[ -z "${BLACK}" ]] && BLACK="\\033[38;5;16m"
+[[ -z "${GREEN}" ]] && GREEN="\\033[38;5;22m"
+[[ -z "${CYAN}" ]] && CYAN="\\033[38;5;123m"
+[[ -z "${PURPLE}" ]] && PURPLE="\\033[01;35m"
+[[ -z "${PURPLE_BLUE}" ]] && PURPLE_BLUE="\\033[38;5;93m"
+[[ -z "${GRAY241}" ]] && GRAY241="\\033[38;5;241m"
+[[ -z "${YELLOW226}" ]] && YELLOW226="\\033[38;5;226m"
+[[ -z "${YELLOW}" ]] && YELLOW="\\033[01;33m"
+[[ -z "${RESET}" ]] && RESET="\\033[0m"
+[[ -z "${RESET_PROMPT}" ]] && RESET_PROMPT="[0m"
+[[ -z "${RED}" ]] && RED="\\033[38;5;1m"
+[[ -z "${BRIGHT_BLUE87}" ]] && BRIGHT_BLUE87="\\033[38;5;87m"
 
 #
 # COLORS - Ouput - end
@@ -113,11 +125,11 @@ PRINTCOMMAND="-l --print0";
 FOUND=0
 
 # Test to see if file exists first
-if [ ! -f "${FILE}" ] ; then
-  {
-    echo -e "${reset} File:\n      ${FILE} ${red} NOT Found! ${reset} ";
-    exit 1;
-  }
+if [[ ! -f "${FILE}" ]] ; then
+{
+  echo -e "${RESET} File:\n      ${FILE} ${RED} NOT Found! ${RESET} ";
+  exit 1;
+}
 fi
 
 
@@ -137,18 +149,20 @@ trap '{ msg_red " KEYBOARD INTERRUPT."; exit 130; }' INT
 #
 test_positives(){
   KIND=""
+  local -i _err=0
   if ls werwerwerwerwerwerwerwerwerwerwerr >/dev/null 2>&1; then
-    if (( $? == 0 )) ;  then  # Intel processor
+    _err=$?
+    if (( _err == 0 )) ;  then  # Intel processor
       KIND="INTEL"
     fi
-    if [ $? == 0 ]; then   # Mac Intel processor
+    if [ $_err == 0 ]; then   # Mac Intel processor
       KIND="${KIND}MAC"
     fi
   else
-    if (( $? == 0 )) ;  then  # Intel processor
+    if (( _err == 0 )) ;  then  # Intel processor
       KIND="INTEL"
     fi
-    if [ $? == 0 ]; then   # Mac Intel processor
+    if [ $_err == 0 ]; then   # Mac Intel processor
       KIND="${KIND}MAC"
     fi
   fi
@@ -173,6 +187,7 @@ check_replacer () {
 
     #stdout UND stderr -capture  REF: https://www.thomas-krenn.com/de/wiki/Bash_stdout_und_stderr_umleiten
     ${REPLACER}  --version &> /tmp/ersetze_test_${REPLACER}.txt
+    # shellcheck disable=SC2155
     local PROPERLYWORKING=$(cat /tmp/ersetze_test_${REPLACER}.txt)
 
     if [[ "$PROPERLYWORKING" == *"dyld:"* ]]; then { echo "error"; return;} fi
@@ -252,38 +267,38 @@ fi
 # S E E K I N G   I N S T A L L    C H E C K  - Start
 #
 if command -v sift >/dev/null 2>&1; then
+{
+  if [ $VERBOSE -eq 1 ] ; then
   {
-      if [ $VERBOSE -eq 1 ] ; then
-        {
-            #  NOT Colored
-            if [ ! -z "$COLORED" ] ; then
-                {
-                  echo " sift INSTALLED."
-                }
-              else
-                {
+    #  NOT Colored
+    if [[ -n "$COLORED" ]] ; then
+    {
+      echo " sift INSTALLED."
+    }
+    else
+    {
                   msg_green " sift INSTALLED."
-                }
-              fi
+    }
+    fi
 
-        }
-      fi
-      # -i, --ignore-case      case insensitive (default: off) Case sentive by default
-      # -n, --line-number      show line numbers (default: off)
-      # -Q, --literal          treat pattern as literal, quote meta characters
-      # --output-sep=          output separator (default: "\n")
-      # --no-color             disable colored output
-      # Error: sift Error: files skipped due to very long lines
-      # Fix:
-      #   REF: https://github.com/svent/sift/issues/16
-      #    As of version 0.4.0 sift supports two new options:
-      #
-      #    --err-skip-line-length to skip these errors
-      #    --blocksize to specify a larger blocksize, allowing to search files with very long lines. Example: --blocksize 10M
-        SEEKER="sift -nQ  --blocksize 50M";
-        IGNORE_DIR="exclude-dirs";
-        IGNORE_FILE="exclude-files";
-        PRINTCOMMAND="-l --output-sep=\"\\x00\"";
+  }
+  fi
+  #-i, --ignore-case      case insensitive (default: off) Case sentive by default
+  #-n, --line-number      show line numbers (default: off)
+  #-Q, --literal          treat pattern as literal, quote meta characters
+  #--output-sep=          output separator (default: "\n")
+  #--no-color             disable colored output
+  # Error: sift Error: files skipped due to very long lines
+  # Fix:
+  #   REF: https://github.com/svent/sift/issues/16
+  #    As of version 0.4.0 sift supports two new options:
+  #
+  #    --err-skip-line-length to skip these errors
+  #    --blocksize to specify a larger blocksize, allowing to search files with very long lines. Example: --blocksize 10M
+  SEEKER="sift -nQ  --blocksize 50M";
+  IGNORE_DIR="exclude-dirs";
+  IGNORE_FILE="exclude-files";
+  PRINTCOMMAND="-l --output-sep=\"\\x00\"";
 }
 else
 {
@@ -309,9 +324,9 @@ else
     if command -v ack >/dev/null 2>&1; then
     {
       msg_green " ack INSTALLED."
-      # ack is case sensitve by default
-      # --print0 Print null byte as separator between filenames, only works with -f, -g, -l, -L or -c.
-      # -Q, --literal                 Quote all metacharacters; PATTERN is litera
+      # ack is            case sensitve by default
+      # --print0          Print null byte as separator between filenames, only works with -f, -g, -l, -L or -c.
+      # -Q, --literal     Quote all metacharacters; PATTERN is litera
       # --nocolor         Highlight the matching text (default: on unless --nocolor)
       #
       # Ack DOES NOT SUPPORT HIDDING LINE NUMBERS
@@ -328,7 +343,7 @@ else
 
       ls ./ack  | egrep 'ack' &>/dev/null
       err_buff=$?
-      if [[ "${PROCESSOR_ERROR}" == "MAC" ]] && [ $err_buff == 1 ]; then
+      if [[ "${PROCESSOR_ERROR}" == *"MAC"* ]] && [ $err_buff == 0 ]; then
       {
         msg_green " ./ack INSTALLED."
         SEEKER="./ack -Q ";
@@ -367,6 +382,7 @@ else
           #-F, --fixed-strings
           # Interpret pattern as a set of fixed strings (i.e. force grep to behave as fgrep).
           # --color=never     disable color
+
           #
           # grep (GNU grep) 2.25
           # -l, --files-with-matches
@@ -434,7 +450,7 @@ if command -v "${DEFAULTSEEKER}" >/dev/null 2>&1; then
   }
   fi
   # make case sentive for ag
-  if [ $DEFAULTSEEKER == "ack" ]; then
+  if [[ "$DEFAULTSEEKER" == "ack" ]] ; then
   {
     SEEKER="ack -Q "
     IGNORE_DIR="ignore-dir";
@@ -443,7 +459,7 @@ if command -v "${DEFAULTSEEKER}" >/dev/null 2>&1; then
   }
   fi
   # make case sentive for local ./ack
-  if [ $DEFAULTSEEKER == "./ack" ]; then
+  if [ -e "./ack" ] && [[ "$DEFAULTSEEKER" == "./ack" ]] ; then
   {
     SEEKER="./ack -Q "
     IGNORE_DIR="ignore-dir";
@@ -452,7 +468,7 @@ if command -v "${DEFAULTSEEKER}" >/dev/null 2>&1; then
   }
   fi
   # use extended expressions
-  if [ $DEFAULTSEEKER == "grep" ]; then
+  if [[ "$DEFAULTSEEKER" == "grep" ]] ; then
   {
     SEEKER="grep -rnE "
     IGNORE_DIR="exclude-dir";
@@ -557,13 +573,13 @@ IGNORELIST=""
 
     while read -r ONE_FILENAME; do
       # if not empty
-      if [ ! -z "${ONE_FILENAME}" ] ; then
+      if [[ -n "${ONE_FILENAME}" ]] ; then
         IGNORELIST="${IGNORELIST} ${EXCLUDEFILE}${ONE_FILENAME}"
       fi
     done <<< "${FILESTOEXCLUDE}"
     while read -r ONE_DIRNAME; do
       # if not empty
-      if [ ! -z "${ONE_DIRNAME}" ] ; then
+      if [[ -n "${ONE_DIRNAME}" ]] ; then
         IGNORELIST="${IGNORELIST} ${EXCLUDEDIR}${ONE_DIRNAME}"
       fi
     done <<< "${DIRSTOEXCLUDE}"
@@ -837,20 +853,20 @@ if [[ $SEEKING == *"/"* || $IMPLACING == *"/"* ]]; then
       # sed
       {
         if [[ "${REPLACERGNU}" == "YES" ]] ; then
-          # sed GNU
-          {
+        # sed GNU
+        {
             echo "${cyan}   sed -i -e s/\"${SEEKING}\"/\"${IMPLACING}\"/g ${FILE}"
                             sed -i -e s/"$SEEKING"/"$IMPLACING"/g ${FILE} | ${SEEKER} "$SEEKING" ${FILESCOMMAND} &>/dev/null
 #                            err_buff=$?
-          }
+        }
         else
-          # sed mac
-          # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
-          {
+        # sed mac
+        # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+        {
             echo "${cyan}   sed  -i'.sedbak'  -e s/\"${SEEKING}\"/\"${IMPLACING}\"/g" ${FILE}
                             sed  -i'.sedbak'  -e s/"$SEEKING"/"$IMPLACING"/g ${FILE} | ${SEEKER} "$SEEKING" ${FILESCOMMAND}  &>/dev/null
 #                            err_buff=$?
-          }
+        }
         fi
       }
     else
