fixed bug escaping parenthesis and spaces in eval

diff --git a/gefund b/gefund
--- a/gefund
+++ b/gefund
@@ -2,7 +2,7 @@
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
 #!/usr/bin/env bash
-set -euo pipefail
+# set -euo pipefail
 
 
 function do_gefund() {
@@ -26,21 +26,58 @@ function do_gefund() {
     ACTIONS=('echo -e "\033[38;5;202m{#}\033[38;5;232m:1\033[0m"')
   }
   fi
+  function escape_parenthesis_right {
+		sed 's/[)]/\\\)/g'
+  }
+
+ function escape_parenthesis_left {
+		sed 's/[(]/\\\(/g'
+  }
+
+ function escape_spaces {
+		sed 's/\ /\\\ /g'
+  }
 
   .each() {
-      local one_item=""
-      local act=""
-      local cmd=""
-      while IFS= read -r one_item; do
+	  function _trap_on_error(){
+    local -ir __trapped_error_exit_num="${2:-0}"
+    echo -e "\\n \033[01;7m*** 0tasks_base/sudoer.bash:$LINENO load_struct_testing() ERROR TRAP $THISSCRIPTNAME \\n${BASH_SOURCE}:${BASH_LINENO[-0]} ${FUNCNAME[1]}() \\n$0:${BASH_LINENO[1]} ${FUNCNAME[2]}()  \\n$0:${BASH_LINENO[2]} ${FUNCNAME[3]}() \\n ERR ...\033[0m  \n \n "
+
+    echo ". ${1}"
+    echo ". exit  ${__trapped_error_exit_num}  "
+    echo ". caller $(caller) "
+    echo ". ${BASH_COMMAND}"
+    local -r __caller=$(caller)
+    local -ir __caller_line=$(echo "${__caller}" | cut -d' ' -f1)
+    local -r __caller_script_name=$(echo "${__caller}" | cut -d' ' -f2)
+    awk 'NR>L-10 && NR<L+10 { printf "%-10d%10s%s\n",NR,(NR==L?"☠ » » » > ":""),$0 }' L="${__caller_line}" "${__caller_script_name}"
+
+    # $(eval ${BASH_COMMAND}  2>&1; )
+    # echo -e " ☠ ${LIGHTPINK} Offending message:  ${__bash_error} ${RESET}"  >&2
+    exit 1
+  }
+	   trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR INT
+    local one_item=""
+    local act=""
+    local cmd=""
+    while IFS= read -r one_item; do
+    {
+        [[ -z "${one_item}" ]] && continue
+        for act in "${ACTIONS[@]}"; do
         {
-          [[ -z "${one_item}" ]] && continue
-          for act in "${ACTIONS[@]}"; do
-            {
-              cmd="${act//\{\#\}/"${one_item}"}"
-                eval "${cmd}"
-              }
-          done
+					# DEBUG echo ">>>"
+					# DEBUG echo  "${one_item}"
+					local escaped="$(escape_spaces <<< "${one_item}" | escape_parenthesis_left | escape_parenthesis_right )"
+					# DEBUG echo "===="
+          cmd="${act//\{\#\}/"${escaped}"}"
+          # BROKE cmd="${act//\{\#\}/"${one_item}"}" # CASE echo ""text (1).pdf" = syntax error near unexpected token `('
+					# DEBUG echo "----"
+					# DEBUG echo  "${cmd}"
+					# DEBUG echo "<<<"
+          eval "${cmd}"
         }
+        done
+    }
     done
   } # end .each
 
