improved download script

diff --git a/install_sublime_dev b/install_sublime_dev
--- a/install_sublime_dev
+++ b/install_sublime_dev
@@ -3,26 +3,36 @@
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
 #
-#load_struct_testing_wget(){
-#    local provider="/_/clis/execute_command_intuivo_cli/struct_testing"
-#    [   -e "${provider}"  ] && source "${provider}"
-#    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
-#    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
-#} # end load_struct_testing_wget
-#load_struct_testing_wget
+load_struct_testing_wget(){
+    local provider="/_/clis/execute_command_intuivo_cli/struct_testing"
+    [   -e "${provider}"  ] && source "${provider}"
+    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+    ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
+} # end load_struct_testing_wget
+load_struct_testing_wget
 
 get_lastest_sublime_version() {
     local SUBLIMEDEVLASTESTBUILD=$(curl -L https://www.sublimetext.com/3dev  2>/dev/null | grep 'Text 3 dev build is ....' | cut -c44-47)  # suppress only wget download messages, but keep wget output for variable
     wait
-    #assert not empty "${SUBLIMEDEVLASTESTBUILD}"
+    [[ -z "${SUBLIMEDEVLASTESTBUILD}" ]] && failed "Sublime Version not found!"
     echo "${SUBLIMEDEVLASTESTBUILD}"
+}
+download_sublime(){
+  # sample https://download.sublimetext.com/sublime-text_build-3133_amd64.deb
+  if ( command -v type wget >/dev/null 2>&1; ) ; then
+   wget --quiet --no-check-certificate "https://download.sublimetext.com/${1}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
+  elif ( command -v type curl >/dev/null 2>&1; ); then
+    curl -O "https://download.sublimetext.com/${1}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
+  else
+    failed "I cannot find wget or curl to download! https://download.sublimetext.com/${1}"
+  fi
 }
 install_darwin_lastest_sublime_64() {
     local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
     local SUBLIMENAME="Sublime%20Text%20Build%20${SUBLIMEDEVLASTESTBUILD}.dmg"
     wait
     cd ~/Downloads/
-    curl -O https://download.sublimetext.com/${SUBLIMENAME}
+    download_sublime "${SUBLIMENAME}"
     wait
     sudo hdiutil attach ${SUBLIMENAME}
     wait
@@ -37,7 +47,7 @@ install_linux_lastest_sublime_64() {
     local SUBLIMENAME="sublime-text_build-${SUBLIMEDEVLASTESTBUILD}_amd64.deb"
     wait
     cd ~/Downloads/
-    curl -O https://download.sublimetext.com/${SUBLIMENAME}
+    download_sublime "${SUBLIMENAME}"
     wait
     sudo dpkg -i ${SUBLIMENAME}
     wait
@@ -48,7 +58,7 @@ install_linux_lastest_sublime_32() {
     local SUBLIMENAME="sublime-text_build-${SUBLIMEDEVLASTESTBUILD}_i386.deb"
     wait
     cd ~/Downloads/
-    curl -O https://download.sublimetext.com/${SUBLIMENAME}
+    download_sublime "${SUBLIMENAME}"
     wait
     sudo dpkg -i ${SUBLIMENAME}
     wait
