added echoing comments to sublime install

diff --git a/install_sublime_dev b/install_sublime_dev
--- a/install_sublime_dev
+++ b/install_sublime_dev
@@ -4,7 +4,7 @@
 #
 #
 load_struct_testing_wget(){
-    local provider="/_/clis/execute_command_intuivo_cli/struct_testing"
+    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
     [   -e "${provider}"  ] && source "${provider}"
     [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
     ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
@@ -12,10 +12,26 @@ load_struct_testing_wget(){
 load_struct_testing_wget
 
 get_lastest_sublime_version() {
-    local SUBLIMEDEVLASTESTBUILD=$(curl -L https://www.sublimetext.com/3dev  2>/dev/null | sed -n "/<p\ class=\"latest\">/,/<\/div>/p" | head -1 | grep 'Build ....' | cut -c42-45)  # suppress only wget download messages, but keep wget output for variable
-    wait
-    [[ -z "${SUBLIMEDEVLASTESTBUILD}" ]] && failed "Sublime Version not found!"
-    echo "${SUBLIMEDEVLASTESTBUILD}"
+    local _sublime_string=$(curl -L https://www.sublimetext.com/3dev  2>/dev/null | sed -n "/<p\ class=\"latest\">/,/<\/div>/p" | head -1)  # suppress only wget download messages, but keep wget output for variable
+    local _sublime_build_line=$(echo "${_sublime_string}" | grep 'Build ....')
+    if [ -z "${_sublime_build_line}" ] ; then
+    {
+        echo "error when doing check of line string from website. Got nothing"
+        echo "    _sublime_string: <${_sublime_string}>"
+        echo "                      0123456789 123456789 123456789 123456789 123456789 123456789 1234567889 123456789 123456789 123456789 123456789 "
+        echo "                                1         2         3         4         5         6          7         8         9        10        11"
+        echo "_sublime_build_line: <${_sublime_build_line}>"
+        failed "Error"
+        exit 69;
+    }
+    else
+    {
+        local SUBLIMEDEVLASTESTBUILD=$(echo "${_sublime_build_line}" | cut -c42-45)
+        wait
+        [[ -z "${SUBLIMEDEVLASTESTBUILD}" ]] && failed "Sublime Version not found!"
+        echo "${SUBLIMEDEVLASTESTBUILD}"
+    }
+    fi
 }
 download_sublime(){
   # sample https://download.sublimetext.com/sublime-text_build-3133_amd64.deb
@@ -43,12 +59,18 @@ install_darwin_lastest_sublime_64() {
 } # end install_darwin_lastest_sublime_64
 
 install_linux_lastest_sublime_64() {
+    echo "checking version"
     local SUBLIMEDEVLASTESTBUILD=$(get_lastest_sublime_version)
+    echo " version ${SUBLIMEDEVLASTESTBUILD}"
     local SUBLIMENAME="sublime-text_build-${SUBLIMEDEVLASTESTBUILD}_amd64.deb"
+    echo " looking for file ${SUBLIMENAME} online"
     wait
+    echo "changing to Downloads folder  ~/Downloads/"
     cd ~/Downloads/
+    echo "downloading ${SUBLIMENAME}"
     download_sublime "${SUBLIMENAME}"
     wait
+    echo "installing "
     sudo dpkg -i ${SUBLIMENAME}
     wait
 } # end install_linux_lastest_sublime_64
