added to_this to_this script updated ersetze and nur to not ignore some folders and updated copy_from_to

diff --git a/nur b/nur
--- a/nur
+++ b/nur
@@ -336,6 +336,94 @@ PROCESSOR_ERROR=$(test_positives)
 # C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --End
 #
 
+#
+# C H E C K   R E P L A C E   F U N C T I O N S   I N S T A L L E D  --Start
+#
+check_replacer () {
+  local REPLACER="$1"
+  if command -v "${REPLACER}" >/dev/null 2>&1; then
+    # It looks installed
+    # .. is it working properly
+    # msg_green " ${1} INSTALLED."
+
+    #stdout UND stderr -capture  REF: https://www.thomas-krenn.com/de/wiki/Bash_stdout_und_stderr_umleiten
+    ${REPLACER}  --version &> /tmp/ersetze_test_${REPLACER}.txt
+    local PROPERLYWORKING=$(cat /tmp/ersetze_test_${REPLACER}.txt)
+
+    if [[ "$PROPERLYWORKING" == *"dyld:"* ]]; then { echo "error"; return;} fi
+    if [[ $PROPERLYWORKING == *"GNU"* ]]; then { echo "GNU"; return;} else { echo "MAC";return;} fi
+    echo "checked";
+    return;
+  else
+    # msg_red "${green} ${red} CANNOT REPLACE ...${1} IS MISSING ";
+    # msg_red " NEED TO INSTALL ${1}.       Linux:    sudo apt-get install ${1}         Mac:     brew install ${1}   "
+    echo "install";
+    return;
+  fi
+}
+msg_install () {
+  msg_red "${green} ${red} CANNOT REPLACE ...${1} IS MISSING ";
+  msg_red " NEED TO INSTALL ${1}.       Linux:    sudo apt-get install ${1}         Mac:     brew install ${1}   "
+}
+# REPLACER="sed";
+# Try vim's ex
+REPLACER="sed";
+VALIDREPLACER=$(check_replacer "${REPLACER}")
+
+
+if [[ $VALIDREPLACER == "error" ]] ; then
+  msg_red "Error with replacer ${REPLACER}"
+  msg_red " - Error:"
+  cat /tmp/ersetze_test_${REPLACER}.txt
+   rm /tmp/ersetze_test_${REPLACER}.txt
+fi
+
+if [[ $VALIDREPLACER == "install" ]] ; then
+  msg_install "${REPLACER}"
+fi
+rm /tmp/ersetze_test_${REPLACER}.txt
+
+# TODO - Remove Repetition HERE
+# ? empty still
+if [[ $VALIDREPLACER == "install" || $VALIDREPLACER == "error"  ]] ; then
+  REPLACER="sed";
+  VALIDREPLACER=$(check_replacer "${REPLACER}")
+
+  if [[ $VALIDREPLACER == "error" ]] ; then
+    msg_red "Error with replacer ${REPLACER}"
+    msg_red " - Error:"
+    cat /tmp/ersetze_test_${REPLACER}.txt
+     rm /tmp/ersetze_test_${REPLACER}.txt
+    exit 1;
+  fi
+
+  if [[ $VALIDREPLACER == "install" ]] ; then
+    msg_install "${REPLACER}"
+    rm /tmp/ersetze_test_${REPLACER}.txt
+    exit 1;
+  fi
+fi
+
+
+
+REPLACERGNU="NO"
+if [[ $VALIDREPLACER == "GNU" ]] ; then
+  REPLACERGNU="YES"
+fi
+
+# Test
+# echo "REPLACERGNU: $REPLACERGNU"
+# echo "VALIDREPLACER: $VALIDREPLACER"
+# exit
+# C H E C K   R E P L A C E   F U N C T I O N S   I N S T A L L E D  -- RESULTS
+# Results as
+#             $REPLACERGNU  NO OR YES
+#             $REPLACERGNU  ex or sed
+#             halts execution if not found
+#
+# C H E C K   R E P L A C E   F U N C T I O N S   I N S T A L L E D  -- End
+
+
 if command -v sift >/dev/null 2>&1; then
   {
 
@@ -882,7 +970,7 @@ DIRSTOEXCLUDE=".cargo
 .gvfs
 .git
 .vagrant
-.idea
+
 .servo
 coverage
 AbsoluteUrlBundle
@@ -890,13 +978,13 @@ app/Stubs
 bower_components
 cache
 dist
-node_modules
+
 python
 storage/debugbar
 storage/logs
 target
-tmp
-log
+
+
 ports
 var/cache
 var/logs
@@ -1007,19 +1095,60 @@ then
     # not PIPED
     if [ -z "$PIPED" ]; then
       {
+            if [[ "${REPLACERGNU}" == "YES" ]] ; then
+          # sed GNU
+          {
+            echo "${yellow} sed GNU ";
             #${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  &>/dev/null
-            RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's\\\\\\g')
+            RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed -e 's\\\\\\g')
+          }
+        else
+          # sed mac
+          # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+          {
+            echo "${yellow} sed MAC ";
+            #${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  &>/dev/null
+            RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed -e 's\\\\\\g')
+
+          }
+        fi
       }
     else # YES PIPED
       {
             # NOT Colored
             if [ ! -z "$COLORED" ] ; then
               {
-                echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""$SEEKING"g
+                if [[ "${REPLACERGNU}" == "YES" ]] ; then
+                  # sed GNU
+                  {
+                    echo "${yellow} sed GNU ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""$SEEKING"g
+                  }
+                else
+                  # sed mac
+                  # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+                  {
+                    echo "${yellow} sed MAC ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""$SEEKING"g
+                  }
+                fi
               }
             else
               {
-                echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""[38;5;196m$SEEKING${RESET_PROMPT}"g
+                if [[ "${REPLACERGNU}" == "YES" ]] ; then
+                  # sed GNU
+                  {
+                    echo "${yellow} sed GNU ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""[38;5;196m$SEEKING${RESET_PROMPT}"g
+                  }
+                else
+                  # sed mac
+                  # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+                  {
+                    echo "${yellow} sed MAC ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  | sed 's\\\\\\g' | sed s"$SEEKING""[38;5;196m$SEEKING${RESET_PROMPT}"g
+                  }
+                fi
               }
             fi
       }
@@ -1046,9 +1175,22 @@ else
         # not PIPED
     if [ -z "$PIPED" ]; then
       {
-
-            #${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  &>/dev/null
-            RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g')
+                if [[ "${REPLACERGNU}" == "YES" ]] ; then
+                  # sed GNU
+                  {
+                    echo "${yellow} sed GNU ";
+                    #${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  &>/dev/null
+                    RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g')
+                  }
+                else
+                  # sed mac
+                  # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+                  {
+                    echo "${yellow} sed MAC ";
+                    #${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST}  &>/dev/null
+                    RESULT=$(${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g')
+                  }
+                fi
 
       }
     else # YES PIPED
@@ -1056,11 +1198,37 @@ else
             # NOT Colored
             if [ ! -z "$COLORED" ] ; then
               {
-                echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g'  | sed s/"$SEEKING"/"$SEEKING"/g
+                if [[ "${REPLACERGNU}" == "YES" ]] ; then
+                  # sed GNU
+                  {
+                    echo "${yellow} sed GNU ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g'  | sed s/"$SEEKING"/"$SEEKING"/g
+                  }
+                else
+                  # sed mac
+                  # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+                  {
+                    echo "${yellow} sed MAC ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g'  | sed s/"$SEEKING"/"$SEEKING"/g
+                  }
+                fi
               }
             else
               {
-                echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g' | sed s/"$SEEKING"/"[38;5;196m$SEEKING${RESET_PROMPT}"/g
+                if [[ "${REPLACERGNU}" == "YES" ]] ; then
+                  # sed GNU
+                  {
+                    echo "${yellow} sed GNU ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g' | sed s/"$SEEKING"/"[38;5;196m$SEEKING${RESET_PROMPT}"/g
+                  }
+                else
+                  # sed mac
+                  # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+                  {
+                    echo "${yellow} sed MAC ";
+                    echo "$PIPED" | ${SEEKER} "$SEEKING" ${FILESCOMMAND}      ${IGNORELIST} | sed 's@\\@\\\\@g' | sed s/"$SEEKING"/"[38;5;196m$SEEKING${RESET_PROMPT}"/g
+                  }
+                fi
               }
             fi
       }
@@ -1123,7 +1291,20 @@ if [[ "${FOUND}" == "YES" ]] ; then
         cut -f1 -d":" <<< "$RESULT" > /tmp/tmp1.txt #filename     or      'binary file matches'
         # File linenumber
         cut -f2 -d":" <<< "$RESULT" > /tmp/tmp2.txt #line number  or 'filename' with ^ the above
-        cut -f3 -d":" <<< "$RESULT" | sed 's^ *g' | sed 's^\t*g' > /tmp/tmp4.txt #first results
+        if [[ "${REPLACERGNU}" == "YES" ]] ; then
+          # sed GNU
+          {
+            echo "${yellow} sed GNU ";
+            cut -f3 -d":" <<< "$RESULT" | sed 's^ *g' | sed 's^\t*g' > /tmp/tmp4.txt #first results
+          }
+        else
+          # sed mac
+          # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+          {
+            echo "${yellow} sed MAC ";
+            cut -f3 -d":" <<< "$RESULT" | sed 's^ *g' | sed 's^\t*g' > /tmp/tmp4.txt #first results
+          }
+        fi
 
         #RESULT=$(cat /tmp/tmp4.txt)
         cut -f4 -d":" <<< "$RESULT" > /tmp/tmp6.txt
@@ -1145,14 +1326,34 @@ if [[ "${FOUND}" == "YES" ]] ; then
             awk '{print $0}' /tmp/tmp4.txt > /tmp/tomp4.txt #RESET color  # first results
 
             # the rest of the results
-            cat /tmp/tomp4.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp4.txt   #first results
-            cat /tmp/tmp6.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp6.txt
-            cat /tmp/tmp8.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp8.txt
-            cat /tmp/tmp10.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp10.txt
-            cat /tmp/tmp12.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp12.txt
-            cat /tmp/tmp14.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp14.txt
-            cat /tmp/tmp16.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp16.txt
-            cat /tmp/tmp18.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp18.txt
+            if [[ "${REPLACERGNU}" == "YES" ]] ; then
+              # sed GNU
+              {
+                echo "${yellow} sed GNU ";
+                cat /tmp/tomp4.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp4.txt   #first results
+                cat /tmp/tmp6.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp6.txt
+                cat /tmp/tmp8.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp8.txt
+                cat /tmp/tmp10.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp10.txt
+                cat /tmp/tmp12.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp12.txt
+                cat /tmp/tmp14.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp14.txt
+                cat /tmp/tmp16.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp16.txt
+                cat /tmp/tmp18.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp18.txt
+              }
+            else
+              # sed mac
+              # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+              {
+                echo "${yellow} sed MAC ";
+                cat /tmp/tomp4.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp4.txt   #first results
+                cat /tmp/tmp6.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp6.txt
+                cat /tmp/tmp8.txt  | sed s"$SEEKING""$SEEKING"g > /tmp/temp8.txt
+                cat /tmp/tmp10.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp10.txt
+                cat /tmp/tmp12.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp12.txt
+                cat /tmp/tmp14.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp14.txt
+                cat /tmp/tmp16.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp16.txt
+                cat /tmp/tmp18.txt | sed s"$SEEKING""$SEEKING"g > /tmp/temp18.txt
+              }
+            fi
           }
         else
           {
@@ -1169,14 +1370,34 @@ if [[ "${FOUND}" == "YES" ]] ; then
             awk '{print "[0m" $0}' /tmp/tmp4.txt  > /tmp/tomp4.txt #RESET color  # first results
 
             # the rest of the results
-            cat /tmp/tomp4.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp4.txt
-            cat /tmp/tmp6.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp6.txt
-            cat /tmp/tmp8.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp8.txt
-            cat /tmp/tmp10.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp10.txt
-            cat /tmp/tmp12.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp12.txt
-            cat /tmp/tmp14.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp14.txt
-            cat /tmp/tmp16.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp16.txt
-            cat /tmp/tmp18.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp18.txt
+            if [[ "${REPLACERGNU}" == "YES" ]] ; then
+              # sed GNU
+              {
+                echo "${yellow} sed GNU ";
+                cat /tmp/tomp4.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp4.txt
+                cat /tmp/tmp6.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp6.txt
+                cat /tmp/tmp8.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp8.txt
+                cat /tmp/tmp10.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp10.txt
+                cat /tmp/tmp12.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp12.txt
+                cat /tmp/tmp14.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp14.txt
+                cat /tmp/tmp16.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp16.txt
+                cat /tmp/tmp18.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp18.txt
+              }
+            else
+              # sed mac
+              # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+              {
+                echo "${yellow} sed MAC ";
+                cat /tmp/tomp4.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp4.txt
+                cat /tmp/tmp6.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp6.txt
+                cat /tmp/tmp8.txt  | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp8.txt
+                cat /tmp/tmp10.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp10.txt
+                cat /tmp/tmp12.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp12.txt
+                cat /tmp/tmp14.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp14.txt
+                cat /tmp/tmp16.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp16.txt
+                cat /tmp/tmp18.txt | sed s"$SEEKING""[38;5;9m$SEEKING${RESET_PROMPT}"g > /tmp/temp18.txt
+              }
+            fi
           }
         fi
 
@@ -1221,7 +1442,20 @@ if [[ "${FOUND}" == "YES" ]] ; then
         #cat /tmp/temp19.txt # This cat was leading errors in display  ...notice the missing chars before "uiload"
         # Fixed cat version
         #cat /tmp/temp19.txt | sed 's^:g' | sed 's:$g' | sed 's:.$g' | sed 's:.$g'  | sed 's.$g'
-        cat /tmp/temp19.txt | sed 's^:g' | sed 's:*$g' #| sed 's:*$g' #| sed 's:$g'  #| sed 's.$g'
+        if [[ "${REPLACERGNU}" == "YES" ]] ; then
+          # sed GNU
+          {
+            echo "${yellow} sed GNU ";
+            cat /tmp/temp19.txt | sed 's^:g' | sed 's:*$g' #| sed 's:*$g' #| sed 's:$g'  #| sed 's.$g'
+          }
+        else
+          # sed mac
+          # MAC REPLACER Has to HAVE A FILENAME.EXTENSION provided for the -i (inplace) option
+          {
+            echo "${yellow} sed MAC ";
+            cat /tmp/temp19.txt | sed 's^:g' | sed 's:*$g' #| sed 's:*$g' #| sed 's:$g'  #| sed 's.$g'
+          }
+        fi
         #        ➜  en ü download_and_write
         #
         # download_and_write
