updated remove script to stop to allow cancel and observe to better know if empty var

diff --git a/remove b/remove
--- a/remove
+++ b/remove
@@ -1,3 +1,4 @@
+#!/usr/bin/env bash
 #!/bin/bash
 # @author Zeus Intuivo <zeus@intuivo.com>
 #
@@ -33,10 +34,29 @@ function escape_doublequotes {
 }
 
 
+continue_y_n() {
+   read -p "CONTINUE Y/[N]: CONTROL C to STOP " reply
+   reply=${reply:-N}
+   echo $reply
+} # end continue_y_n
+echo "remove all files called *${SEEKING}* in subfolders recursively !!!?  "
+THE_ANSWER=$(continue_y_n)
+echo THE_ANSWER:${THE_ANSWER}
+if [[ "${THE_ANSWER}" == "y" ||  "${THE_ANSWER}" == "Y" ]]  ; then
+{
+  echo "..remove !!"
+}
+else
+{
+  echo "..aborted!!"
+  exit 0
+}
+fi
 #
 # C H E C K   R E P L A C E   F U N C T I O N S   I N S T A L L E D  --Start
 #
 check_version_data () {
+  local -i  _err
   local REPLACER="$1"
   if command -v "${REPLACER}" >/dev/null 2>&1; then
     # It looks installed
@@ -44,11 +64,28 @@ check_version_data () {
     # msg_green " ${1} INSTALLED."
 
     #stdout UND stderr -capture  REF: https://www.thomas-krenn.com/de/wiki/Bash_stdout_und_stderr_umleiten
-    ${REPLACER}  --version &> /tmp/ersetze_test_${REPLACER}.txt
-    local PROPERLYWORKING=$(cat /tmp/ersetze_test_${REPLACER}.txt)
+    ${REPLACER}  --version &> /tmp/cp_or_sed_command_test_${REPLACER}.txt
+    _err=$?
+    local PROPERLYWORKING=$(cat /tmp/cp_or_sed_command_test_${REPLACER}.txt)
 
+
+    if [[ "$(uname)" == "Darwin" ]] ; then
+      # Do something under Mac OS X platform
+      if [ ${_err} -eq 64 ] && [[ "$PROPERLYWORKING" == *"illegal option -- -"* ]]; then { echo "MAC"; return;} fi
+
+    elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+      # Do something under GNU/Linux platform
+      echo " ";
+
+    elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+      # Do something under Windows NT platform
+      echo " ";
+
+      # nothing here
+    fi
     if [[ "$PROPERLYWORKING" == *"dyld:"* ]]; then { echo "error"; return;} fi
     if [[ $PROPERLYWORKING == *"GNU"* ]]; then { echo "GNU"; return;} else { echo "MAC";return;} fi
+    if  [ ${_err} -ne 0 ] ; then { echo "error"; return;} fi
     echo "checked";
     return;
   else
@@ -70,14 +107,14 @@ VALIDREPLACER=$(check_version_data "${REPLACER}")
 if [[ $VALIDREPLACER == "error" ]] ; then
   msg_red "Error with replacer ${REPLACER}"
   msg_red " - Error:"
-  cat /tmp/ersetze_test_${REPLACER}.txt
-   rm /tmp/ersetze_test_${REPLACER}.txt
+  cat /tmp/cp_or_sed_command_test_${REPLACER}.txt
+   rm /tmp/cp_or_sed_command_test_${REPLACER}.txt
 fi
 
 if [[ $VALIDREPLACER == "install" ]] ; then
   msg_install "${REPLACER}"
 fi
-rm /tmp/ersetze_test_${REPLACER}.txt
+rm /tmp/cp_or_sed_command_test_${REPLACER}.txt
 
 # TODO - Remove Repetition HERE
 # ? empty still
@@ -88,14 +125,14 @@ if [[ $VALIDREPLACER == "install" || $VALIDREPLACER == "error"  ]] ; then
   if [[ $VALIDREPLACER == "error" ]] ; then
     msg_red "Error with replacer ${REPLACER}"
     msg_red " - Error:"
-    cat /tmp/ersetze_test_${REPLACER}.txt
-     rm /tmp/ersetze_test_${REPLACER}.txt
+    cat /tmp/cp_or_sed_command_test_${REPLACER}.txt
+     rm /tmp/cp_or_sed_command_test_${REPLACER}.txt
     exit 1;
   fi
 
   if [[ $VALIDREPLACER == "install" ]] ; then
     msg_install "${REPLACER}"
-    rm /tmp/ersetze_test_${REPLACER}.txt
+    rm /tmp/cp_or_sed_command_test_${REPLACER}.txt
     exit 1;
   fi
 fi
@@ -120,6 +157,9 @@ fi
 # C H E C K   R E P L A C E   F U N C T I O N S   I N S T A L L E D  -- End
 
 
+function removal_with_subdirectories() {
+
+
 # Using mv
 #
 #   or
@@ -133,67 +173,93 @@ fi
 # -a, --archive: archive mode; equals -rlptgoD (no -H,-A,-X)
 # --delete-after: delete files on the receiving side be done after the transfer has completed
 # If you've root privileges, prefix with sudo to override potential permission issues.
-
-
+    local CURCOMMAND FILESFOUND1 FILESFOUND2 FILESFOUND3 FILESFOUND4 FILESFOUND
+    local REPLACERGNU
+    REPLACERGNU="${1}"
+    local SEEKING
+    SEEKING="${*:2}"
+    [ -z ${SEEKING} ] && return;
     CURCOMMAND="find . -name \"*${SEEKING}*\" -print0  | xargs -0 -I {} mv {} /tmp/ "
     # dotglob:
     #      If set, Bash includes filenames beginning with a ‘.’ in the results of filename expansion.
-    shopt -s dotglob
-    echo -e "\033[38;5;27m ====   \033[38;5;214m $(echo "${CURCOMMAND}")       \033[38;5;27m      ====\n";
-    #find . -name "*${SEEKING}*" -print0 | xargs -0 rm
-    FILESFOUND=$(find . -name "*${SEEKING}*" | cut -c 3-)
-    if [ ! -z "${FILESFOUND}" ] ; then
-      echo -e "\033[38;5;147m "
-      echo "${FILESFOUND} "
-      echo -e "\n"
-      #find . -name "*${SEEKING}*" -print0  | xargs -0 -I {} mv {} /tmp/
+    shopt -s dotglob   # Notice this is a bash script #!/usr/bin/env bash as stated on the header
+    #
+    # find . -name "*${SEEKING}*" -print0 | xargs -0 rm
+    #    This echo  $(echo "${CURCOMMAND}")   is work around ...if removed
+    #      it outputs only this    ====    CURCOMMAND  ==== "
+    #
+    CURCOMMAND="find . -name \"${SEEKING}\" -print0  | xargs -0 -I {} mv {} /tmp/ "
+    echo -e "\033[38;5;27m ====   \033[38;5;214m $(echo "${CURCOMMAND}")           \033[38;5;27m     ====";
+    FILESFOUND1="$(find . -name "${SEEKING}")"
 
-      while read -r ONE_FULLPATH_FILENAME; do
-        # if not empty
-        if [ ! -z "${ONE_FULLPATH_FILENAME}" ] ; then
-          JUST_FILENAME=$(basename "${ONE_FULLPATH_FILENAME}")
-          echo -e "\033[38;5;27m ..copying...  \033[38;5;214m $(echo "cp -Rrf ${ONE_FULLPATH_FILENAME} /tmp/")       \033[38;5;27m      ";
-          if [[ "${REPLACERGNU}" == "YES" ]] ; then
-          # cp GNU
-          {
-            echo "${yellow} cp GNU "; 
-            cp -Rrf "${ONE_FULLPATH_FILENAME}" /tmp/
-          }
-          else
-          # cp mac
-          {
-            echo "${yellow} cp MAC ";    
-            cp -rf "${ONE_FULLPATH_FILENAME}" /tmp/    
-          }
-          fi
-          echo -e "\033[38;5;27m ..cleaning..  \033[38;5;214m $(echo "rm -rf ${ONE_FULLPATH_FILENAME} ")       \033[38;5;27m      ";
-          rm -rf "${ONE_FULLPATH_FILENAME}"
-          #echo -e "\033[38;5;27m ..removing..   \033[38;5;214m $(echo "rm -rf ${ONE_FULLPATH_FILENAME}")       \033[38;5;27m      ";
-          #rm -rf """${ONE_FULLPATH_FILENAME}"""
-        fi
-      done <<< "${FILESFOUND}"
-    fi
+    CURCOMMAND="find . -name \"${SEEKING}*\" -print0  | xargs -0 -I {} mv {} /tmp/ "
+    echo -e "\033[38;5;27m   ====   \033[38;5;214m $(echo "${CURCOMMAND}")        \033[38;5;27m   ====";
+    FILESFOUND2="$(find . -name "${SEEKING}*")"
+
+    CURCOMMAND="find . -name \"*${SEEKING}\" -print0  | xargs -0 -I {} mv {} /tmp/ "
+    echo -e "\033[38;5;27m     ====   \033[38;5;214m $(echo "${CURCOMMAND}")    \033[38;5;27m   ====";
+    FILESFOUND3="$(find . -name "*${SEEKING}")"
+
+    CURCOMMAND="find . -name \"*${SEEKING}*\" -print0  | xargs -0 -I {} mv {} /tmp/ "
+    echo -e "\033[38;5;27m       ====   \033[38;5;214m $(echo "${CURCOMMAND}")\033[38;5;27m  ====";
+    FILESFOUND4="$(find . -name "*${SEEKING}*")"
+    FILESFOUND="${FILESFOUND1}
+${FILESFOUND2}
+${FILESFOUND3}
+${FILESFOUND4}"
+    [ -z ${FILESFOUND} ] && echo -e "\033[38;5;27m         ====   \033[38;5;214m Nothing found !\033[38;5;27m  ====" && return;
+    echo -e "\033[38;5;147m "
+    echo "${FILESFOUND} "
+    echo -e "\n"
+    #find . -name "*${SEEKING}*" -print0  | xargs -0 -I {} mv {} /tmp/
+    local ONE_FULLPATH_FILENAME ONE_FULLPATH_FILENAME JUST_FILENAME
+    while read -r ONE_FULLPATH_FILENAME; do
+      # if not empty
+      [ -z ${ONE_FULLPATH_FILENAME} ] && continue
+      JUST_FILENAME=$(basename "${ONE_FULLPATH_FILENAME}")
+      echo -e "\033[38;5;27m ..copying...  \033[38;5;214m $(echo "cp -Rrf ${ONE_FULLPATH_FILENAME} /tmp/")       \033[38;5;27m      ";
+      if [[ "${REPLACERGNU}" == "YES" ]] ; then
+      # cp GNU
+      {
+        echo "${yellow} cp GNU ";
+        cp -Rrf "${ONE_FULLPATH_FILENAME}" /tmp/
+      }
+      else
+      # cp mac
+      {
+        echo "${yellow} cp MAC ";
+        cp -rf "${ONE_FULLPATH_FILENAME}" /tmp/
+      }
+      fi
+      echo -e "\033[38;5;27m ..cleaning..  \033[38;5;214m $(echo "rm -rf ${ONE_FULLPATH_FILENAME} ")       \033[38;5;27m      ";
+      rm -rf "${ONE_FULLPATH_FILENAME}"
+      #echo -e "\033[38;5;27m ..removing..   \033[38;5;214m $(echo "rm -rf ${ONE_FULLPATH_FILENAME}")       \033[38;5;27m      ";
+      #rm -rf """${ONE_FULLPATH_FILENAME}"""
+
+      echo -e "\033[38;5;27m  and moved to /tmp/           \033[38;5;214m";
+      echo " ";
+    done <<< "$(cut -c 3- <<<"${FILESFOUND}" | sort | uniq)"
+} # end removal_with_subdirectories
+
+removal_with_subdirectories "${REPLACERGNU}"  "${SEEKING}"
+
 # check operation systems
 
-  if [[ "$(uname)" == "Darwin" ]] ; then
-    # Do something under Mac OS X platform
-    echo " ";
+#   if [[ "$(uname)" == "Darwin" ]] ; then
+#     # Do something under Mac OS X platform
+#     echo " ";
 
-  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
-    # Do something under GNU/Linux platform
-    echo " ";
+#   elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+#     # Do something under GNU/Linux platform
+#     echo " ";
 
-  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
-    # Do something under Windows NT platform
-    echo " ";
+#   elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+#     # Do something under Windows NT platform
+#     echo " ";
 
-    # nothing here
-  fi
-
-
-
-echo -e "\033[38;5;27m  and moved to /tmp/           \033[38;5;214m";
-echo " ";
+#     # nothing here
+#   fi
 
 
-echo " "
+
+# echo " "
